# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Flutter Module 工程的相对路径。一般情况下，我们会把 iOS项目与 Flutter Module 放在同一个目录下
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo
  install_all_flutter_pods(flutter_application_path)

end
